### ISSUE TITLE
smrt suite is downloaded to /tmp using all available disk.

### ISSUE THREAD

**Issue by Slugger70** [gvlproject/gvl.ansible.smrt_analysis#1]
smrt suite is temporarily downloaded to /tmp using all available disk on /. Therefore, if there is less than 2GB free it fails.

There is a fix and I'll submit a pull request shortly.

**Comment by tseemann** [comment]
I recall you moved `/tmp` off root disk?

**Comment by Slugger70** [comment]
Moved /tmp on machines to transient storage.

**Comment by Slugger70** [comment]
Fixed in git head. 4.0.0 release needs to be deprecated.
